### ISSUE TITLE
How can I use Double numbers?

### ISSUE THREAD

**Issue by makarna35** [Gruzer/simple-gauge-android#1]
How can I use double numbers with gauge?
example: 1.20  52.15 etc...

**Comment by Gruzer** [comment]
> How can I use double numbers with gauge?
> example: 1.20 52.15 etc...

Min/Max/Value all accept double number(Ranges Too)
for example:
`Gauge.minValue= 10.1
  Gauge.maxValue = 150.3
  Gauge.value = 35.6`
