### ISSUE TITLE
textColor in the ArcGauge

### ISSUE THREAD

**Issue by Fadiabikhalil94** [Gruzer/simple-gauge-android#11]
hello, thanks for this good work of yours, but I can't find a way to change the text color of the value inside an ArcGauge.
I'm using a black background which makes the value not visible to the user.
thanks for your time

**Comment by Gruzer** [comment]
> hello, thanks for this good work of yours, but I can't find a way to change the text color of the value inside an ArcGauge.
> I'm using a black background which makes the value not visible to the user.
> thanks for your time

Hi sorry for late response
currently for some unknow for me reason i forgot to set option to change text color
in future release I will fix this issue

I will remain this issue open

**Comment by Gruzer** [comment]
Hi 
[in new release 0.3.0](https://github.com/Gruzer/simple-gauge-android/releases/tag/0.3.0)
u have option to set you custom value color

Best Regards 
Gruzer
