### ISSUE TITLE
negative range issue

### ISSUE THREAD

**Issue by DominikReber** [Gruzer/simple-gauge-android#12]
There is an issue with negativ range:

       val range = Range()
        range.color = Color.parseColor("#ce0000")
        range.from = -10.0
        range.to = 0.0
       

        val range2 = Range()
        range2.color = Color.parseColor("#E3E500")
        range2.from =0.0
        range2.to = 10.0

        val range3 = Range()
        range3.color = Color.parseColor("#00b20b")
        range3.from = 10.0
        range3.to = 20.0
        val range4 = Range()
        range4.color = Color.parseColor("#cc0000")
        range4.from = 20.0
        range4.to = 30.0
        val range5 = Range()
        range5.color = Color.parseColor("#ff0000")
        range5.from = 30.0
        range5.to = 40.0

        //add color ranges to gauge
        halfGauge1.addRange(range)
        halfGauge1.addRange(range2)
        halfGauge1.addRange(range3)
        halfGauge1.addRange(range4)
        halfGauge1.addRange(range5)

        //set min max and current value
        halfGauge1.minValue = -10.0
        halfGauge1.maxValue = 40.0
        halfGauge1.value = 0.0

The Gauge is not formatted well (negativ value is way too big)

**Comment by Gruzer** [comment]
> There is an issue with negativ range:
> 
> ```
>    val range = Range()
>     range.color = Color.parseColor("#ce0000")
>     range.from = -10.0
>     range.to = 0.0
>    
> 
>     val range2 = Range()
>     range2.color = Color.parseColor("#E3E500")
>     range2.from =0.0
>     range2.to = 10.0
> 
>     val range3 = Range()
>     range3.color = Color.parseColor("#00b20b")
>     range3.from = 10.0
>     range3.to = 20.0
>     val range4 = Range()
>     range4.color = Color.parseColor("#cc0000")
>     range4.from = 20.0
>     range4.to = 30.0
>     val range5 = Range()
>     range5.color = Color.parseColor("#ff0000")
>     range5.from = 30.0
>     range5.to = 40.0
> 
>     //add color ranges to gauge
>     halfGauge1.addRange(range)
>     halfGauge1.addRange(range2)
>     halfGauge1.addRange(range3)
>     halfGauge1.addRange(range4)
>     halfGauge1.addRange(range5)
> 
>     //set min max and current value
>     halfGauge1.minValue = -10.0
>     halfGauge1.maxValue = 40.0
>     halfGauge1.value = 0.0
> ```
> 
> The Gauge is not formatted well (negativ value is way too big)

Hi and thx for bug report
will fix it in next release

have a great day
best regards
Gruzer

**Comment by DominikReber** [comment]
Thanks, great gauge!

**Comment by Gruzer** [comment]
Hi 
in release 0.3.1 this bug fixed

Best regards 
Gruzer
