### ISSUE TITLE
Is it possible to set the min and max value to int instead of double?

### ISSUE THREAD

**Issue by sujayisiri** [Gruzer/simple-gauge-android#13]
Hi, I have integrated half gauge into my app and i want to set the min and max value of the gauge to an integer value. Is it possible to do it?

halfGaugeScoreMeter.minValue = 0
halfGaugeScoreMeter.maxValue = 1000
halfGaugeScoreMeter.value = 500

If I set the above values I get an error to set the value double instead of int.

**Comment by Gruzer** [comment]
Hi and thx
i will add option to set custom number formatting

**Comment by Gruzer** [comment]
Hi 
[in new release 0.3.0](https://github.com/Gruzer/simple-gauge-android/releases/tag/0.3.0)
u have option to set you custom number formatter 

Best Regards 
Gruzer
