### ISSUE TITLE
cant make it work on API 19 

### ISSUE THREAD

**Issue by yatiir** [Gruzer/simple-gauge-android#15]
i'm having this issue if any one can help please !! 

Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.Gruzer:simple-gauge-android:0.3.1] C:\Users\hp\.gradle\caches\transforms-2\files-2.1\902f89fc26344acd7be3c25a03baffcc\jetified-simple-gauge-android-0.3.1\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.ekn.gruzer.gaugelibrary" to force usage (may lead to runtime failures)

**Comment by Gruzer** [comment]
Hi
Sorry but min SDK version is 21.
Just increase your project's minSdk version to at least 21,
