### ISSUE TITLE
Show Label on range

### ISSUE THREAD

**Issue by lillogoal** [Gruzer/simple-gauge-android#16]
Hi,

i used since one month this library, it is the best.

I have a question, i would like to show  each range min,max added to guage, is possible ?

Thanks

**Comment by Gruzer** [comment]
> Hi,
> 
> i used since one month this library, it is the best.
> 
> I have a question, i would like to show each range min,max added to guage, is possible ?
> 
> Thanks

Hi
Sorry for late response 

can you provide more details how you see it
