### ISSUE TITLE
Gauge Width

### ISSUE THREAD

**Issue by LisaKipfer** [Gruzer/simple-gauge-android#17]
It would be great if there would be an option to change the width of the Gauge (BG width) :)

**Comment by Gruzer** [comment]
> It would be great if there would be an option to change the width of the Gauge (BG width) :)


Hi
Sorry for late response 

can u provide more details  as far I remember u can change width of view but aspect ratio of gauge will be remain
if you can give more details about your problem I'll  be happy to help
