### ISSUE TITLE
Does not work with negative ranges.

### ISSUE THREAD

**Issue by MFrat** [Gruzer/simple-gauge-android#2]
Example:

```

        HalfGauge halfGauge = findViewById(R.id.halfGauge);

        Range range = new Range();
        range.setColor(Color.parseColor("#ce0000"));
        range.setFrom(0.0);
        range.setTo(-50);

        Range range2 = new Range();
        range2.setColor(Color.parseColor("#E3E500"));
        range2.setFrom(-50);
        range2.setTo(-70);

        Range range3 = new Range();
        range3.setColor(ContextCompat.getColor(this, R.color.colorAccent));
        range3.setFrom(-70);
        range3.setTo(-100);

        //add color ranges to gauge
        halfGauge.addRange(range);
        halfGauge.addRange(range2);
        halfGauge.addRange(range3);

        //set min max and current value
        halfGauge.setMinValue(0.0);
        halfGauge.setMaxValue(-100);
        halfGauge.setValue(-80);
```

**Comment by Gruzer** [comment]
Ok and  thank you 
i will add support for negative ranges, values in next version

**Comment by Gruzer** [comment]
> Example:
> 
> ```
> 
>         HalfGauge halfGauge = findViewById(R.id.halfGauge);
> 
>         Range range = new Range();
>         range.setColor(Color.parseColor("#ce0000"));
>         range.setFrom(0.0);
>         range.setTo(-50);
> 
>         Range range2 = new Range();
>         range2.setColor(Color.parseColor("#E3E500"));
>         range2.setFrom(-50);
>         range2.setTo(-70);
> 
>         Range range3 = new Range();
>         range3.setColor(ContextCompat.getColor(this, R.color.colorAccent));
>         range3.setFrom(-70);
>         range3.setTo(-100);
> 
>         //add color ranges to gauge
>         halfGauge.addRange(range);
>         halfGauge.addRange(range2);
>         halfGauge.addRange(range3);
> 
>         //set min max and current value
>         halfGauge.setMinValue(0.0);
>         halfGauge.setMaxValue(-100);
>         halfGauge.setValue(-80);
> ```

Ok and thank you
i will add support for negative ranges, values in next version

**Comment by Gruzer** [comment]
Hi 

> Example:
> 
> ```
> 
>         HalfGauge halfGauge = findViewById(R.id.halfGauge);
> 
>         Range range = new Range();
>         range.setColor(Color.parseColor("#ce0000"));
>         range.setFrom(0.0);
>         range.setTo(-50);
> 
>         Range range2 = new Range();
>         range2.setColor(Color.parseColor("#E3E500"));
>         range2.setFrom(-50);
>         range2.setTo(-70);
> 
>         Range range3 = new Range();
>         range3.setColor(ContextCompat.getColor(this, R.color.colorAccent));
>         range3.setFrom(-70);
>         range3.setTo(-100);
> 
>         //add color ranges to gauge
>         halfGauge.addRange(range);
>         halfGauge.addRange(range2);
>         halfGauge.addRange(range3);
> 
>         //set min max and current value
>         halfGauge.setMinValue(0.0);
>         halfGauge.setMaxValue(-100);
>         halfGauge.setValue(-80);
> ```

Negative ranges are now working 
new version 0.2.0 available
