### ISSUE TITLE
The half gauge would consume CPU even no value change

### ISSUE THREAD

**Issue by Walelile** [Gruzer/simple-gauge-android#4]
In Android studio vm, the half gauge would consume CPU even no value change. (3% ~ 6%)
It is because there is a thread to perform invalidate() every 5 milliseconds, although it seems for animation.

**Comment by Gruzer** [comment]
Hi
i find a problem its not animation its was LAYER_TYPE_SOFTWARE that cause CPU use 
(more correctly caused invalidation all time)
for now i will switch it to LAYER_TYPE_HARDWARE(hope no one use API below 14 for new apps)
for now  option to disable shadow of needle and background its will solve usage of CPU
in few days i will update dependency for new version

thank you and have a good day

**Comment by rocboronat** [comment]
Hello! Here's another one interested in this update :·)

**Comment by Gruzer** [comment]
Hello
High CPU unreasonable usage when using Half Gauge --fixed
New version 0.2.1 available

Best Regards
Gruzer

**Comment by rocboronat** [comment]
Thanks a lot! 😊
