### ISSUE TITLE
Low values problem

### ISSUE THREAD

**Issue by dxyahia** [Gruzer/simple-gauge-android#6]
there is a small problem related to the arc gauge, when it takes a low value (closer to 0(ex 0.5)) it colorize the entire gauge disc

**Comment by dxyahia** [comment]
there is a small problem related to the arc gauge, when it takes a low value (closer to 0(ex 0.5)) it colorize the entire gauge disc

**Comment by Gruzer** [comment]
Hi
I checked and didn't find any problem 
can you be more specific 
and there is some visual options like 
ArcGauge.isUseRangeBGColor = true/false 
this add color of the range(according to value) with alpha   to entire gauge disc as background
try to set false in ArcGauge.isUseRangeBGColor = false
and see if this solve your problem

Best Regards

**Comment by Gruzer** [comment]
Cause no response  and i didn't find any problem and not  receive additional information
i closing an issue 

Best Regards
