### ISSUE TITLE
How to remove the Color BackGround?

### ISSUE THREAD

**Issue by bayermatheus** [Gruzer/simple-gauge-android#7]
How could I remove de gray color BackGround of strokes or change them for a black color? I don't know if that is possible.
Sorry if this is a dumb question, I'm pretty new with Android. 
Anyway, thank you already! This gauge library is awesome!

**Comment by Gruzer** [comment]
Hi
sorry for late response 
currently there is no option for this 
i will try do add it in feature release

**Comment by Gruzer** [comment]
> How could I remove de gray color BackGround of strokes or change them for a black color? I don't know if that is possible.
> Sorry if this is a dumb question, I'm pretty new with Android.
> Anyway, thank you already! This gauge library is awesome!

Hi 
i add option to change  background color for strokes in new version 0.2.2
you can set  transparent color to remove background color

Code Example

```java
Gauge.setGaugeBackGroundColor(Color.LTGRAY)
```

Best Regards 
Gruzer

**Comment by bayermatheus** [comment]
> > How could I remove de gray color BackGround of strokes or change them for a black color? I don't know if that is possible.
> > Sorry if this is a dumb question, I'm pretty new with Android.
> > Anyway, thank you already! This gauge library is awesome!
> 
> Hi
> i add option to change background color for strokes in new version 0.2.2
> you can set transparent color to remove background color
> 
> Code Example
> 
> ```java
> Gauge.setGaugeBackGroundColor(Color.LTGRAY)
> ```
> 
> Best Regards
> Gruzer


Already using the new version! 
This helped me so much!
Thanks a lot!
