### ISSUE TITLE
How to speed up or delete at all the animation in HalfGauge

### ISSUE THREAD

**Issue by AEEM1993** [Gruzer/simple-gauge-android#8]
Hi Gruzer,
I'm using your gauge in a report. To do so I'm taking a screenshot of the view and saving it in .jpg file, at the press of a button (onClick event) and later placing this image in my report. The problem is that when I haven't waited long enough (time it takes the needle to reach the vaule)  and I press the button the screenshot is taken while the needle hasn't arrive to the final position so the value indicated by the gauge doesnt match the written numerical value in my report

The obvious solution is to wait for a while until the needle reaches position, but this application is supossed to work in industrial enviroment so I'm pretty sure users won't wait so I'll have reports with value mistakenly indicated by the gauge. So far, as a solution, I have created another thread (background worker) where I disable the button for a while (6s) and then the button is enable so the gauge screenshot is taken. 

Is there a better way to acomplish this?
Could the animation be deleted?
Could is be faster?

Thank u in advance for your response, hope to hear soon from you

AEEM1993
Ecuador

**Comment by Gruzer** [comment]
> Hi Gruzer,
> I'm using your gauge in a report. To do so I'm taking a screenshot of the view and saving it in .jpg file, at the press of a button (onClick event) and later placing this image in my report. The problem is that when I haven't waited long enough (time it takes the needle to reach the vaule) and I press the button the screenshot is taken while the needle hasn't arrive to the final position so the value indicated by the gauge doesnt match the written numerical value in my report
> 
> The obvious solution is to wait for a while until the needle reaches position, but this application is supossed to work in industrial enviroment so I'm pretty sure users won't wait so I'll have reports with value mistakenly indicated by the gauge. So far, as a solution, I have created another thread (background worker) where I disable the button for a while (6s) and then the button is enable so the gauge screenshot is taken.
> 
> Is there a better way to acomplish this?
> Could the animation be deleted?
> Could is be faster?
> 
> Thank u in advance for your response, hope to hear soon from you
> 
> AEEM1993
> Ecuador



Hi i just release new version 0.2.2
 now you can enable or disable animation of needle

```java
Gauge.enableAnimation(true/false)
```

Best Regards
Gruzer
