### ISSUE TITLE
How to change needle color

### ISSUE THREAD

**Issue by afacchin73** [Gruzer/simple-gauge-android#9]
Hi,
I need to change the needle color and value text because I would like to use a black background in may app.
Is it Possible?
Thank you

**Comment by etka98** [comment]
Hi,
@afacchin73 if u find way to change needle color and value text, can u write here?

**Comment by Gruzer** [comment]
> Hi,
> I need to change the needle color and value text because I would like to use a black background in may app.
> Is it Possible?
> Thank you

Hi Sorry for late response 
if it still relevant 
you can change color of needle like this example

` HalfGauge.setNeedleColor(Color.MAGENTA)`

**Comment by Gruzer** [comment]
> Hi,
> @afacchin73 if u find way to change needle color and value text, can u write here?

Hi Sorry for late response
if it still relevant
you can change color of needle like this example

HalfGauge.setNeedleColor(Color.MAGENTA)
